# Simple workflow for deploying static content to GitHub Pages
name: CD
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  deploy_to_render:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.RENDER_SERVICE_ID }}
            api_key: ${{ secrets.RENDER_API_KEY }}
            wait_deploy: true
  
